### ISSUE TITLE
Update to support lib 26?

### ISSUE THREAD

**Issue by AdamMc331** [androidessence/MaterialDesignSpecs#20]
It sounds nice, but if we do, we're required to bump Min SDK to 14 instead of 9. This may be okay, but wanted it discussed by all contributors. cc @Mauker1

**Comment by Mauker1** [comment]
I believe that'll be mostly beneficial, since less than 1% of the Android users are still using a phone with API < 14. Also, the updates contains many bug fixes.

**Comment by AdamMc331** [comment]
+1, added this to the current PR.
