### ISSUE TITLE
Create a method to get randomAccent by color name or level.

### ISSUE THREAD

**Issue by Mauker1** [androidessence/MaterialDesignSpecs#5]
It would be useful to have a method such as `getAccentColorByName()` and `getAccentColorByLevel()` for completeness.

**Comment by AdamMc331** [comment]
I am going to close this, as it turns out these methods exist already - https://github.com/androidessence/MaterialDesignSpecs/blob/develop/lib/src/main/java/com/androidessence/materialdesignspecs/MaterialPalettes.java#L312-L335

**Comment by AdamMc331** [comment]
Reoppening as we need an accent color random method.
